import { NextResponse } from 'next/server';

const exampleDocumentId = 'YOUR_DOCUMENT_ID';
const exampleReportId = 'YOUR_REPORT_ID_OR_SEARCH_NAME';

export async function GET() {
  const baseUrl = '/api/agent';
  const docsMarkdown = [
    '# EMIS XML Agent API',
    '',
    'This API is designed for AI agents that need to inspect EMIS XML business logic.',
    '',
    '## Purpose',
    '',
    '- Load an EMIS XML document and receive a `documentId`.',
    '- List and search reports within that document.',
    '- Fetch a report logic summary focused on business rules rather than terminology expansion.',
    '- Inspect cross-report dependencies and parent population relationships.',
    '',
    '## Core Workflow',
    '',
    '1. `POST /api/agent/load-xml` with `multipart/form-data` containing `xmlFile`.',
    `2. Use the returned \`documentId\` with \`${baseUrl}/documents/:documentId/reports\` or \`${baseUrl}/documents/:documentId/search?q=...\`.`,
    '3. Fetch a specific report using `/api/agent/documents/:documentId/reports/:reportId`.',
    '4. For implementation work, prefer `POST /api/agent/query` with `action = getImplementationGuide`.',
    '5. Optionally use `POST /api/agent/query` for other deterministic task-style actions.',
    '',
    '## Important Response Fields',
    '',
    '- `report.parentPopulation`: rendered population context.',
    '- `report.parentChain`: recursive summaries of upstream parent reports.',
    '- `report.libraryItems`: inferred library-item labels surfaced on report index entries.',
    '- `report.agentInterpretation.dependencies.libraryItems`: inferred library-item labels from wrapper reports in the same XML.',
    '- `report.agentInterpretation.decisionFlow`: per-rule decision summary.',
    '- `report.agentInterpretation.inclusionCriteria`: required/include clauses.',
    '- `report.agentInterpretation.exclusionCriteria`: exclusion clauses.',
    '- `report.agentInterpretation.booleanLogic`: compact boolean-like expression.',
    '- `report.agentInterpretation.plainEnglishSummary`: readable logic summary.',
    '- `report.logicMarkdown`: markdown export of the rule structure.',
    '- `report.implementationGuideMarkdown`: combined parent-chain and target-report implementation guide.',
    '',
    '## Example URLs',
    '',
    `- GET ${baseUrl}`,
    `- POST ${baseUrl}/load-xml`,
    `- GET ${baseUrl}/documents/${exampleDocumentId}`,
    `- GET ${baseUrl}/documents/${exampleDocumentId}/reports`,
    `- GET ${baseUrl}/documents/${exampleDocumentId}/search?q=valproate`,
    `- GET ${baseUrl}/documents/${exampleDocumentId}/reports/${encodeURIComponent(exampleReportId)}`,
    `- GET ${baseUrl}/documents/${exampleDocumentId}/graph`,
    `- POST ${baseUrl}/query`,
    '',
    '## Query Route Actions',
    '',
    '- `documentSummary`',
    '- `listReports`',
    '- `searchReports`',
    '- `getReportLogic`',
    '- `getImplementationGuide`',
    '- `getGraph`',
  ].join('\n');

  return NextResponse.json({
    success: true,
    schemaVersion: '1',
    name: 'EMIS XML Agent API',
    purpose: 'Expose parsed EMIS XML business logic to AI agents using deterministic JSON endpoints.',
    docsMarkdown,
    endpoints: [
      {
        name: 'Load XML',
        method: 'POST',
        path: `${baseUrl}/load-xml`,
        contentType: 'multipart/form-data',
        request: {
          fields: [
            {
              name: 'xmlFile',
              type: 'file',
              required: true,
              description: 'EMIS XML export file.',
            },
          ],
        },
        response: {
          success: 'boolean',
          schemaVersion: 'string',
          document: {
            id: 'string',
            fileName: 'string',
            createdAt: 'ISO timestamp',
            xmlSha256: 'string',
            reportCount: 'number',
            parsedAt: 'ISO timestamp',
          },
        },
      },
      {
        name: 'Document Summary',
        method: 'GET',
        path: `${baseUrl}/documents/:documentId`,
        response: {
          success: 'boolean',
          schemaVersion: 'string',
          document: {
            id: 'string',
            fileName: 'string',
            createdAt: 'ISO timestamp',
            xmlSha256: 'string',
            parsedAt: 'ISO timestamp',
            reportCount: 'number',
            reports: 'ReportIndexEntry[]',
          },
        },
      },
      {
        name: 'List Reports',
        method: 'GET',
        path: `${baseUrl}/documents/:documentId/reports`,
        response: {
          success: 'boolean',
          schemaVersion: 'string',
          document: {
            id: 'string',
            fileName: 'string',
            createdAt: 'ISO timestamp',
            reportCount: 'number',
          },
          reports: 'ReportIndexEntry[]',
        },
      },
      {
        name: 'Search Reports',
        method: 'GET',
        path: `${baseUrl}/documents/:documentId/search?q=term`,
        response: {
          success: 'boolean',
          schemaVersion: 'string',
          query: 'string',
          resultCount: 'number',
          results: 'ReportIndexEntry[]',
        },
      },
      {
        name: 'Get Report Logic',
        method: 'GET',
        path: `${baseUrl}/documents/:documentId/reports/:reportId`,
        response: {
          success: 'boolean',
          schemaVersion: 'string',
          document: {
            id: 'string',
            fileName: 'string',
          },
          report: {
            id: 'string',
            xmlId: 'string',
            title: 'string',
            searchName: 'string',
            description: 'string | null',
            folderPath: 'string',
            reportType: 'population | listReport',
            parentPopulation: 'string',
            counts: 'ReportCounts',
            libraryItems: 'LibraryItemReferenceSummary[]',
            agentInterpretation: {
              decisionFlow: 'RuleDecisionSummary[]',
              dependencies: 'ReportDependencySummary',
              inclusionCriteria: 'string[]',
              exclusionCriteria: 'string[]',
              booleanLogic: 'string | null',
              plainEnglishSummary: 'string',
            },
            parentChain: 'ParentChainEntry[]',
            valueSets: 'ValueSetSummary[]',
            logicMarkdown: 'string',
            implementationGuideMarkdown: 'string',
          },
          raw: {
            criteriaGroups: 'CriteriaGroup[]',
            columnGroups: 'ColumnGroup[]',
            valueSets: 'EmisValueSet[]',
          },
        },
      },
      {
        name: 'Document Graph',
        method: 'GET',
        path: `${baseUrl}/documents/:documentId/graph`,
        response: {
          success: 'boolean',
          schemaVersion: 'string',
          document: {
            id: 'string',
            fileName: 'string',
          },
          graph: {
            nodes: 'GraphNode[]',
            edges: 'GraphEdge[]',
          },
        },
      },
      {
        name: 'Task Wrapper',
        method: 'POST',
        path: `${baseUrl}/query`,
        contentType: 'application/json',
        request: {
          documentId: 'string',
          action: 'documentSummary | listReports | searchReports | getReportLogic | getImplementationGuide | getGraph',
          reportId: 'string (required for getReportLogic and getImplementationGuide)',
          q: 'string (required for searchReports)',
        },
        response: 'Matches the underlying endpoint for the chosen action.',
      },
    ],
    examples: {
      curlLoadXml: `curl -X POST http://localhost:3000${baseUrl}/load-xml -F "xmlFile=@C:/path/to/file.xml"`,
      querySearchReports: {
        method: 'POST',
        url: `http://localhost:3000${baseUrl}/query`,
        body: {
          documentId: exampleDocumentId,
          action: 'searchReports',
          q: 'valproate',
        },
      },
      queryGetReportLogic: {
        method: 'POST',
        url: `http://localhost:3000${baseUrl}/query`,
        body: {
          documentId: exampleDocumentId,
          action: 'getReportLogic',
          reportId: exampleReportId,
        },
      },
      queryGetImplementationGuide: {
        method: 'POST',
        url: `http://localhost:3000${baseUrl}/query`,
        body: {
          documentId: exampleDocumentId,
          action: 'getImplementationGuide',
          reportId: exampleReportId,
        },
      },
    },
  });
}
